"""
Test for the CustomSequence example: Datum Plane from 3 Reference Points

Metrological verification:
    Three reference points in the XY plane (z = 0) uniquely determine a plane
    whose normal is the Z-axis (0, 0, 1). This is used as a deterministic,
    exact assertion — any deviation indicates a geometry error in the sequence.

Structural verification:
    After creation, the sequence must expose exactly 3 child elements (the
    reference points) and 4 sequence elements in total (3 points + 1 plane).
"""

import gom
import gom.api.services

SERVICE_ENDPOINT = 'gom.api.examples.custom_sequence'
SERVICE_TIMEOUT = 10000

SEQUENCE_NAME = 'Test Datum Plane'

# Three reference points that lie in the XY plane (z = 0).
# The expected plane normal is exactly (0, 0, 1).
P1 = (0.0, 0.0, 0.0)
P2 = (100.0, 0.0, 0.0)
P3 = (0.0, 100.0, 0.0)

TOLERANCE = 1e-6


def test_datum_plane_from_3_points():
    """
    Test the CustomSequence datum plane element.

    Checks:
    1. Sequence structure: 3 child elements, 4 sequence elements total.
    2. Plane geometry: normal is aligned with Z-axis for XY-plane input points.
    """
    gom.script.sys.close_project()
    gom.script.sys.create_project()

    service = gom.api.services.get_service(SERVICE_ENDPOINT)
    if not service.get_status() == 'RUNNING':
        if not service.start_and_wait(timeout=SERVICE_TIMEOUT):
            assert False, f"Failed to start service {SERVICE_ENDPOINT}"

    # -------------------------------------------------------------------------
    # Create the datum plane sequence with 3 known XY-plane reference points
    # -------------------------------------------------------------------------
    gom.script.customelements.create_sequence(
        contribution='examples.custom_sequence',
        name=SEQUENCE_NAME,
        values={
            'p1_x': P1[0], 'p1_y': P1[1], 'p1_z': P1[2],
            'p2_x': P2[0], 'p2_y': P2[1], 'p2_z': P2[2],
            'p3_x': P3[0], 'p3_y': P3[1], 'p3_z': P3[2],
        }
    )

    leading = gom.app.project.nominal_elements[SEQUENCE_NAME]

    # -------------------------------------------------------------------------
    # TEST 1: Sequence structure — 3 child reference points must exist.
    # Child names are generated by generate_element_name() as "Leading <sep> Child",
    # where <sep> is an implementation-defined separator character. We therefore
    # match by prefix (sequence name) and suffix ("Reference Point N") to remain
    # independent of the exact separator character.
    # -------------------------------------------------------------------------
    all_nominal_names = [str(e.name) for e in gom.app.project.nominal_elements]
    child_names = [
        n for n in all_nominal_names
        if n.startswith(SEQUENCE_NAME) and 'Reference Point' in n
    ]
    assert len(child_names) == 3, (
        f"Expected 3 reference point child elements, got {len(child_names)}: {child_names}"
    )

    # -------------------------------------------------------------------------
    # TEST 2: Plane geometry — normal must be aligned with Z-axis
    # Three points in the XY plane yield an unambiguous normal of (0, 0, ±1).
    # -------------------------------------------------------------------------
    normal = leading.normal
    gom.log.info(f"Plane normal: ({normal.x}, {normal.y}, {normal.z})")

    assert abs(normal.x) < TOLERANCE, (
        f"Plane normal X component should be 0, got {normal.x}"
    )
    assert abs(normal.y) < TOLERANCE, (
        f"Plane normal Y component should be 0, got {normal.y}"
    )
    assert abs(abs(normal.z) - 1.0) < TOLERANCE, (
        f"Plane normal Z component should be ±1, got {normal.z}"
    )
