name: SBOM
on: [workflow_dispatch]
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate SBOM 
        run: |
          gh ext install advanced-security/gh-sbom
          gh sbom | jq
